version: "3.9"

services:
  app:
    build: ./infra/php
    container_name: laravel-app
    working_dir: /data
    volumes:
      - ./src:/data
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: drawing_app
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    networks:
      - app-network

  web:
    image: nginx:1.25-alpine
    container_name: laravel-web
    ports:
      - "80:80"
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: laravel-db
    ports:
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: drawing_app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
      TZ: Asia/Tokyo
    networks:
      - app-network

volumes:
  db-store:

networks:
  app-network:
    driver: bridge
